const types = {
  // -- SERVER -- //
  CONNECT_TO_SERVER_START: "CONNECT_TO_SERVER_START",
  CONNECT_TO_SERVER_SUCCESS: "CONNECT_TO_SERVER_SUCCESS",
  CONNECT_TO_SERVER_FAILURE: "CONNECT_TO_SERVER_FAILURE",
  // -- IMAGE -- //
  UPLOAD_IMAGE_START: "UPLOAD_IMAGE_START",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILURE: "UPLOAD_IMAGE_FAILURE",

  DELETE_IMAGE_START: "DELETE_IMAGE_START",
  DELETE_IMAGE_SUCCESS: "DELETE_IMAGE_SUCCESS",
  DELETE_IMAGE_FAILURE: "DELETE_IMAGE_FAILURE",
};

export default types;
